version: '3'
services:
  web:
    build: .
    tty: true
    volumes:
      - '.:/app'
    ports:
      - '8888:80'
    working_dir: /app
  db:
    image: mysql:5.7.35
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    ports:
      - '33060:3306'
  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
